apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: shopflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: 430367037730.dkr.ecr.us-east-2.amazonaws.com/shopflow/auth:fa89aee610be7b36db2395e8f26dad3fbe637197
          ports:
            - containerPort: 3002
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: shopflow-secrets
                  key: AUTH_DB_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: shopflow-secrets
                  key: SECRET_KEY
          readinessProbe:
            httpGet:
              path: /auth/health
              port: 3002
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: shopflow
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: ClusterIP
