apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: shopflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: 430367037730.dkr.ecr.us-east-2.amazonaws.com/shopflow/product-service:latest
          ports:
            - containerPort: 3003
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: shopflow-secrets
                  key: PRODUCTS_DB_URL
          readinessProbe:
            httpGet:
              path: /products/health
              port: 3003
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: shopflow
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
  type: ClusterIP
