apiVersion: v1
kind: Secret
metadata:
  name: shopflow-secrets
  namespace: shopflow
type: Opaque
stringData:
  POSTGRES_DB: shopflow
  POSTGRES_USER: shopflow
  POSTGRES_PASSWORD: shopflow_pass
  AUTH_DB_URL: postgresql://shopflow:shopflow_pass@postgres:5432/auth_db
  USERS_DB_URL: postgresql://shopflow:shopflow_pass@postgres:5432/users_db
  PRODUCTS_DB_URL: postgresql://shopflow:shopflow_pass@postgres:5432/products_db
  ORDERS_DB_URL: postgresql://shopflow:shopflow_pass@postgres:5432/orders_db
  SECRET_KEY: change-me-in-production
